name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jvm:
    strategy:
      fail-fast: false
      matrix:
        scala: [ 2.13.10, 2.12.17 ]
        java: [ adopt@1.11, openjdk@1.17.0 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up environment
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Run tests
        run: sbt ++${{ matrix.scala }}  -Dscalac.unused.enabled=true clean fmtCheck test
